"""Language-agnostic core for SKTR."""

from sktr_core.model import (
    AIReview,
    AnalysisDiagnostic,
    Dependency,
    DependencyKind,
    DependencyScope,
    DiagnosticSeverity,
    FileChange,
    Issue,
    IssueCategory,
    IssueSeverity,
    Location,
    Module,
    ReviewContext,
    ReviewResult,
    SourceFile,
    Symbol,
    SymbolKind,
    System,
)
from sktr_core.version import SKTR_VERSION

__all__ = [
    "AIReview",
    "AnalysisDiagnostic",
    "Dependency",
    "DependencyKind",
    "DependencyScope",
    "DiagnosticSeverity",
    "FileChange",
    "Issue",
    "IssueCategory",
    "IssueSeverity",
    "Location",
    "Module",
    "ReviewContext",
    "ReviewResult",
    "SourceFile",
    "Symbol",
    "SymbolKind",
    "System",
    "SKTR_VERSION",
]
