"""Language-agnostic core for SKTR."""

from sktr_core.model import (
    APIExposure,
    AIReview,
    AnalysisDiagnostic,
    Dependency,
    DependencyKind,
    DependencyScope,
    DiagnosticSeverity,
    FileChange,
    Issue,
    IssueCategory,
    IssueSeverity,
    Location,
    Module,
    ReviewContext,
    ReviewResult,
    SourceFile,
    Symbol,
    SymbolKind,
    SymbolVisibility,
    System,
)
from sktr_core.localization import (
    DEFAULT_LANGUAGE,
    SUPPORTED_OUTPUT_LANGUAGES,
    deterministic_language,
    is_output_language_supported,
    normalize_language_tag,
)
from sktr_core.version import SKTR_VERSION

__all__ = [
    "AIReview",
    "APIExposure",
    "AnalysisDiagnostic",
    "Dependency",
    "DependencyKind",
    "DependencyScope",
    "DiagnosticSeverity",
    "FileChange",
    "Issue",
    "IssueCategory",
    "IssueSeverity",
    "Location",
    "Module",
    "ReviewContext",
    "ReviewResult",
    "SourceFile",
    "Symbol",
    "SymbolKind",
    "SymbolVisibility",
    "System",
    "SKTR_VERSION",
    "DEFAULT_LANGUAGE",
    "SUPPORTED_OUTPUT_LANGUAGES",
    "deterministic_language",
    "is_output_language_supported",
    "normalize_language_tag",
]
