from __future__ import annotations

import sys
import re
from dataclasses import dataclass
from pathlib import Path

from rich.console import Console
from rich.markup import escape
from rich.text import Text

from sktr_core.model import AnalysisDiagnostic, Issue, IssueSeverity, ReviewResult
from sktr_core.plugins import Output
from sktr_report.artifact import review_result_to_json
from sktr_report.localization import Translator
from sktr_report.summary import review_breadth, risk_level, risk_score


class TerminalOutput:
    format = "terminal"

    def write(self, result: ReviewResult, destination: str | None = None) -> None:
        content = self.render(result)
        if destination is not None:
            _write_text(destination, Text.from_markup(content).plain)
            return

        Console(file=sys.stdout).print(content)

    def render(self, result: ReviewResult) -> str:
        translator = _translator(result)
        score = risk_score(result)
        breadth = review_breadth(result)
        lines = self._summary_lines(result, score, breadth, translator)
        lines.extend(self._changed_file_lines(result, translator))

        if result.issues:
            lines.extend(["", f"[bold]{translator.text('findings', 'Findings')}[/bold]"])
            lines.extend(self._findings_lines(result.issues, translator))
            lines.extend(
                ["", f"[bold]{translator.text('findings_by_category', 'Findings by Category')}[/bold]"]
            )
            lines.extend(self._category_lines(result.issues, translator))

        if result.diagnostics:
            lines.extend(
                ["", f"[bold]{translator.text('analysis_diagnostics', 'Analysis Diagnostics')}[/bold]"]
            )
            lines.extend(
                _terminal_diagnostic(diagnostic, translator) for diagnostic in result.diagnostics
            )

        if result.ai_review is not None:
            lines.extend(self._ai_review_lines(result, translator))

        suggestions = _suggestions(result, translator)
        if suggestions:
            lines.extend(
                ["", f"[bold]{translator.text('suggested_actions', 'Suggested Actions')}[/bold]"]
            )
            lines.extend(f"- {escape(suggestion)}" for suggestion in suggestions)

        if result.messages:
            lines.extend(["", f"[bold]{translator.text('notes', 'Notes')}[/bold]"])
            lines.extend(f"- {escape(translator.message(message))}" for message in result.messages)

        lines.extend(self._metadata_lines(result, translator))

        return "\n".join(lines)

    def _summary_lines(
        self,
        result: ReviewResult,
        score: int,
        breadth: dict[str, int],
        translator: Translator,
    ) -> list[str]:
        lines = [
            f"[bold]{translator.text('review', 'SKTR Review')}[/bold]",
            "",
            f"[bold]{translator.text('summary', 'Summary')}[/bold]",
            f"{translator.text('risk', 'Risk')}: {translator.severity(risk_level(score))}",
            f"{translator.text('score', 'Score')}: {score}/100",
            f"{translator.text('changed_files', 'Changed files')}: {len(result.context.file_changes)}",
            f"{translator.text('excluded_files', 'Excluded files')}: {len(result.context.excluded_files)}",
            f"{translator.text('issues', 'Issues')}: {len(result.issues)}",
        ]
        if breadth["production_files"] or breadth["modules"]:
            lines.append(
                translator.text(
                    "review_breadth",
                    "Review breadth: {production_files} production files across {modules} modules",
                    production_files=breadth["production_files"],
                    modules=breadth["modules"],
                )
            )
        return lines

    def _changed_file_lines(self, result: ReviewResult, translator: Translator) -> list[str]:
        if not result.context.file_changes:
            message, guidance = _empty_review_state(result, translator)
            lines = [
                "",
                f"[bold]{translator.text('review_state', 'Review State')}[/bold]",
                message,
            ]
            if guidance:
                lines.append(guidance)
            return lines
        return [
            "",
            f"[bold]{translator.text('changed_files', 'Changed Files')}[/bold]",
            *[
                f"{self._status_label(change.status)} {escape(change.path)}"
                for change in result.context.file_changes
            ],
        ]

    def _metadata_lines(self, result: ReviewResult, translator: Translator) -> list[str]:
        lines = [
            "",
            f"[bold]{translator.text('metadata', 'Metadata')}[/bold]",
            translator.text("generated_by", "Generated by SKTR."),
            f"{translator.text('status', 'Status')}: {translator.status(result.status)}",
        ]
        if "output_language" in result.metadata:
            lines.append(
                f"{translator.text('language', 'Language')}: {translator.requested}"
            )
        if result.metadata.get("generated_at"):
            lines.append(
                f"{translator.text('generated_at', 'Generated at')}: "
                f"{escape(str(result.metadata['generated_at']))}"
            )
        if result.context.metadata.get("review_scope"):
            lines.append(
                f"{translator.text('review_scope', 'Review scope')}: "
                f"{translator.scope(str(result.context.metadata['review_scope']))}"
            )
        if result.context.metadata.get("repository_root"):
            lines.append(
                f"{translator.text('repository_root', 'Repository root')}: "
                f"{escape(str(result.context.metadata['repository_root']))}"
            )
        if translator.language == "en" and translator.requested.split("-", 1)[0] != "en":
            lines.append(
                translator.text(
                    "language_fallback",
                    (
                        "Language `{requested}` does not have a complete catalog; deterministic "
                        "text is shown in English and AI content is requested in `{requested}`."
                    ),
                    requested=translator.requested,
                )
            )
        return lines

    def _ai_review_lines(self, result: ReviewResult, translator: Translator) -> list[str]:
        lines = ["", f"[bold]{translator.text('ai_review', 'AI Review')}[/bold]"]
        if result.ai_review.overview:
            lines.extend(
                [
                    f"[bold]{translator.text('overview', 'Overview')}[/bold]",
                    escape(result.ai_review.overview),
                ]
            )
        if result.ai_review.recommendations:
            lines.append("")
            lines.append(
                f"[bold]{translator.text('prioritized_actions', 'Prioritized Actions')}[/bold]"
            )
            lines.extend(self._recommendation_lines(result, translator))
        lines.extend(
            f"[yellow]{translator.text('warning', 'Warning')}:[/yellow] {escape(warning)}"
            for warning in result.ai_review.warnings
        )
        return lines

    def _findings_lines(self, issues: list[Issue], translator: Translator) -> list[str]:
        lines: list[str] = []
        groups = _issue_groups(issues)
        for severity in _SEVERITY_ORDER:
            severity_groups = [group for group in groups if group.severity == severity]
            if not severity_groups:
                continue
            if lines:
                lines.append("")
            lines.append(f"[bold]{translator.severity(severity.value)}[/bold]")
            for group in severity_groups:
                count = (
                    " ("
                    + translator.text(
                        "occurrences",
                        "{count} occurrences",
                        count=len(group.issues),
                    )
                    + ")"
                    if len(group.issues) > 1
                    else ""
                )
                lines.append(
                    f"[yellow]⚠[/yellow] {escape(translator.issue_title(group.issues[0]))}{count}"
                )
                if len(group.issues) == 1:
                    lines.extend(
                        f"  {line}"
                        for line in _terminal_issue_body(group.issues[0], translator)
                    )
                else:
                    lines.append(
                        f"  {translator.text('affected_files', 'Affected files')}: "
                        f"{_format_files(_issue_files(group.issues), markdown=False, translator=translator)}"
                    )
        return lines

    def _category_lines(self, issues: list[Issue], translator: Translator) -> list[str]:
        lines: list[str] = []
        categories = sorted({issue.category for issue in issues}, key=lambda value: value.value)
        for category in categories:
            category_issues = [issue for issue in issues if issue.category == category]
            lines.append(
                f"{translator.category(category.value)}: {len(category_issues)} "
                f"{translator.text('issues', 'issues').lower()} | "
                f"{translator.text('highest_severity', 'highest')} "
                f"{translator.severity(_highest_severity(category_issues).value)} | "
                f"{len(_issue_files(category_issues))} "
                f"{translator.text('file', 'files').lower()}"
            )
        return lines

    def _recommendation_lines(
        self, result: ReviewResult, translator: Translator
    ) -> list[str]:
        assert result.ai_review is not None
        lines: list[str] = []
        for index, item in enumerate(result.ai_review.recommendations, start=1):
            if index > 1:
                lines.append("")
            lines.extend(
                [
                    f"[bold]{index}. {escape(item.title)}[/bold]",
                    f"   {translator.text('why', 'Why')}: {escape(item.why)}",
                    f"   {translator.text('suggested_action', 'Suggested action')}: "
                    f"{escape(item.suggested_action)}",
                ]
            )
            if item.related_files:
                lines.append(
                    f"   {translator.text('related_files', 'Related files')}: "
                    f"{escape(', '.join(item.related_files))}"
                )
        return lines

    def _status_label(self, status: str) -> str:
        return {
            "added": "A",
            "modified": "M",
            "deleted": "D",
            "renamed": "R",
        }.get(status, "?")

class JsonOutput:
    format = "json"

    def write(self, result: ReviewResult, destination: str | None = None) -> None:
        content = review_result_to_json(result)
        if destination is not None:
            _write_text(destination, content)
            return

        sys.stdout.write(content + "\n")


class MarkdownOutput:
    format = "markdown"

    def write(self, result: ReviewResult, destination: str | None = None) -> None:
        content = self.render(result)
        if destination is not None:
            _write_text(destination, content)
            return

        sys.stdout.write(content + "\n")

    def render(self, result: ReviewResult) -> str:
        translator = _translator(result)
        score = risk_score(result)
        breadth = review_breadth(result)
        lines = self._summary_lines(result, score, breadth, translator)
        lines.extend(self._changed_file_lines(result, translator))

        if result.issues:
            lines.append("")
            lines.append(f"## {translator.text('findings', 'Findings')}")
            lines.extend(self._issues_by_severity(result.issues, translator))

            lines.append("")
            lines.append(
                f"## {translator.text('findings_by_category', 'Findings by Category')}"
            )
            lines.extend(self._issues_by_category(result.issues, translator))

        if result.diagnostics:
            lines.extend(
                [
                    "",
                    f"## {translator.text('analysis_diagnostics', 'Analysis Diagnostics')}",
                    (
                        f"| {translator.text('severity', 'Severity')} | "
                        f"{translator.text('analyzer', 'Analyzer')} | "
                        f"{translator.text('file', 'File')} | "
                        f"{translator.text('message', 'Message')} |"
                    ),
                    "|---|---|---|---|",
                ]
            )
            for diagnostic in result.diagnostics:
                lines.append(_markdown_diagnostic(diagnostic, translator))

        if result.ai_review is not None:
            lines.extend(self._ai_review_lines(result, translator))

        suggestions = _suggestions(result, translator)
        if suggestions:
            lines.append("")
            lines.append(
                f"## {translator.text('suggested_actions', 'Suggested Actions')}"
            )
            for suggestion in suggestions:
                lines.append(f"- {suggestion}")

        if result.messages:
            lines.append("")
            lines.append(f"## {translator.text('notes', 'Notes')}")
            lines.extend(f"- {translator.message(message)}" for message in result.messages)

        lines.extend(self._metadata_lines(result, translator))

        return "\n".join(lines)

    def _summary_lines(
        self,
        result: ReviewResult,
        score: int,
        breadth: dict[str, int],
        translator: Translator,
    ) -> list[str]:
        lines = [
            f"# {translator.text('review', 'SKTR Review')}",
            "",
            f"## {translator.text('summary', 'Summary')}",
            f"{translator.text('risk', 'Risk')}: {translator.severity(risk_level(score))}  ",
            f"{translator.text('score', 'Score')}: {score}/100  ",
            f"{translator.text('changed_files', 'Changed files')}: {len(result.context.file_changes)}  ",
            f"{translator.text('excluded_files', 'Excluded files')}: {len(result.context.excluded_files)}  ",
            f"{translator.text('issues', 'Issues')}: {len(result.issues)}",
        ]
        if breadth["production_files"] or breadth["modules"]:
            lines.append(
                translator.text(
                    "review_breadth",
                    "Review breadth: {production_files} production files across {modules} modules",
                    production_files=breadth["production_files"],
                    modules=breadth["modules"],
                )
            )
        return lines

    def _changed_file_lines(self, result: ReviewResult, translator: Translator) -> list[str]:
        if not result.context.file_changes:
            message, guidance = _empty_review_state(result, translator)
            lines = [
                "",
                f"## {translator.text('review_state', 'Review State')}",
                "",
                f"**{message}**",
            ]
            if guidance:
                lines.extend(["", guidance])
            return lines
        lines = [
            "",
            f"## {translator.text('changed_files', 'Changed Files')}",
            (
                f"| {translator.text('status', 'Status')} | "
                f"{translator.text('file', 'File')} |"
            ),
            "|---|---|",
        ]
        lines.extend(
            f"| {self._status_label(change.status)} | {change.path} |"
            for change in result.context.file_changes
        )
        return lines

    def _ai_review_lines(self, result: ReviewResult, translator: Translator) -> list[str]:
        assert result.ai_review is not None
        lines = ["", f"## {translator.text('ai_review', 'AI Review')}"]
        if result.ai_review.overview:
            lines.extend(
                ["", f"### {translator.text('overview', 'Overview')}", result.ai_review.overview]
            )
        if result.ai_review.recommendations:
            lines.extend(
                [
                    "",
                    f"### {translator.text('prioritized_actions', 'Prioritized Actions')}",
                ]
            )
            for index, item in enumerate(result.ai_review.recommendations, start=1):
                lines.extend(
                    [
                        "",
                        f"#### {index}. {item.title}",
                        "",
                        f"**{translator.text('why', 'Why')}:** {item.why}",
                        "",
                        f"**{translator.text('suggested_action', 'Suggested action')}:** "
                        f"{item.suggested_action}",
                    ]
                )
                if item.related_files:
                    lines.extend(
                        ["", f"**{translator.text('related_files', 'Related files')}:**", ""]
                    )
                    lines.extend(f"- `{path}`" for path in item.related_files)
        for warning in result.ai_review.warnings:
            lines.extend(
                ["", f"{translator.text('warning', 'Warning')}: {warning}"]
            )
        return lines

    def _metadata_lines(self, result: ReviewResult, translator: Translator) -> list[str]:
        lines = [
            "",
            f"## {translator.text('metadata', 'Metadata')}",
            translator.text("generated_by", "Generated by SKTR."),
            f"{translator.text('status', 'Status')}: {translator.status(result.status)}",
        ]
        if "output_language" in result.metadata:
            lines.append(
                f"{translator.text('language', 'Language')}: {translator.requested}"
            )
        if result.metadata.get("generated_at"):
            lines.append(
                f"{translator.text('generated_at', 'Generated at')}: "
                f"{result.metadata['generated_at']}"
            )
        if result.context.metadata.get("review_scope"):
            lines.append(
                f"{translator.text('review_scope', 'Review scope')}: "
                f"{translator.scope(str(result.context.metadata['review_scope']))}"
            )
        if result.context.metadata.get("repository_root"):
            lines.append(
                f"{translator.text('repository_root', 'Repository root')}: "
                f"{result.context.metadata['repository_root']}"
            )
        if translator.language == "en" and translator.requested.split("-", 1)[0] != "en":
            lines.append(
                translator.text(
                    "language_fallback",
                    (
                        "Language `{requested}` does not have a complete catalog; deterministic "
                        "text is shown in English and AI content is requested in `{requested}`."
                    ),
                    requested=translator.requested,
                )
            )
        return lines

    def _status_label(self, status: str) -> str:
        return {
            "added": "A",
            "modified": "M",
            "deleted": "D",
            "renamed": "R",
        }.get(status, "?")

    def _issues_by_severity(
        self, issues: list[Issue], translator: Translator
    ) -> list[str]:
        lines: list[str] = []
        groups = _issue_groups(issues)
        for severity in _SEVERITY_ORDER:
            severity_groups = [group for group in groups if group.severity == severity]
            if not severity_groups:
                continue
            lines.append(f"### {translator.severity(severity.value)}")
            lines.extend(self._issue_bullets(severity_groups, translator))
        return lines

    def _issues_by_category(
        self, issues: list[Issue], translator: Translator
    ) -> list[str]:
        lines: list[str] = [
            (
                f"| {translator.text('category', 'Category')} | "
                f"{translator.text('issues', 'Issues')} | "
                f"{translator.text('highest_severity', 'Highest severity')} | "
                f"{translator.text('affected_files', 'Affected files')} | "
                f"{translator.text('rules', 'Rules')} |"
            ),
            "|---|---:|---|---|---|",
        ]
        categories = sorted({issue.category for issue in issues}, key=lambda category: category.value)
        for category in categories:
            category_issues = [issue for issue in issues if issue.category == category]
            lines.append(
                "| "
                f"{translator.category(category.value)} | "
                f"{len(category_issues)} | "
                f"{translator.severity(_highest_severity(category_issues).value)} | "
                f"{_format_files(_issue_files(category_issues), markdown=True, translator=translator)} | "
                f"{self._rule_names(category_issues, translator)} |"
            )
        return lines

    def _rule_names(self, issues: list[Issue], translator: Translator) -> str:
        rules = sorted(
            {
                (
                    translator.issue_title(issue)
                    if translator.language == "es" and issue.metadata.get("rule_key")
                    else issue.metadata.get("rule_name") or issue.rule_id or "unknown"
                )
                for issue in issues
            }
        )
        return ", ".join(str(rule) for rule in rules)

    def _issue_bullets(
        self, groups: list["_IssueGroup"], translator: Translator
    ) -> list[str]:
        lines: list[str] = []
        for group in groups:
            count = (
                " ("
                + translator.text(
                    "occurrences",
                    "{count} occurrences",
                    count=len(group.issues),
                )
                + ")"
                if len(group.issues) > 1
                else ""
            )
            lines.append(f"- **{translator.issue_title(group.issues[0])}**{count}")
            if len(group.issues) == 1:
                lines.extend(
                    f"  {line}"
                    for line in self._issue_body(group.issues[0], translator)
                )
            else:
                lines.append(
                    f"  {translator.text('affected_files', 'Affected files')}: "
                    f"{_format_files(_issue_files(group.issues), markdown=True, translator=translator)}"
                )
        return lines

    def _issue_body(self, issue: Issue, translator: Translator) -> list[str]:
        if issue.metadata.get("rule_key") == "forbidden_dependency":
            source = issue.metadata.get("source", "")
            target = issue.metadata.get("target", "")
            reason = issue.metadata.get("reason") or translator.text(
                "configured_dependency_violation",
                "This violates configured dependency rules.",
            )
            return [
                translator.text(
                    "imports_markdown",
                    "`{source}` imports `{target}`.",
                    source=source,
                    target=target,
                ),
                f"{translator.text('reason', 'Reason')}: {reason}",
            ]

        if issue.metadata.get("rule_key") == "large_function":
            symbol = issue.metadata.get("symbol", issue.title)
            line_count = issue.metadata.get("line_count", "unknown")
            return [
                translator.text(
                    "function_lines_markdown",
                    "`{symbol}` has {count} lines.",
                    symbol=symbol,
                    count=line_count,
                ),
            ]

        return [translator.issue_description(issue)]


_SEVERITY_ORDER = [
    IssueSeverity.CRITICAL,
    IssueSeverity.HIGH,
    IssueSeverity.MEDIUM,
    IssueSeverity.LOW,
    IssueSeverity.INFO,
]

_SEVERITY_WEIGHT = {
    severity: len(_SEVERITY_ORDER) - index
    for index, severity in enumerate(_SEVERITY_ORDER)
}


@dataclass(frozen=True)
class _IssueGroup:
    title: str
    severity: IssueSeverity
    issues: list[Issue]


def _issue_groups(issues: list[Issue]) -> list[_IssueGroup]:
    grouped: dict[tuple[IssueSeverity, str, str | None], list[Issue]] = {}
    for issue in issues:
        grouped.setdefault((issue.severity, issue.title, issue.rule_id), []).append(issue)
    return [
        _IssueGroup(title=title, severity=severity, issues=group_issues)
        for (severity, title, _), group_issues in grouped.items()
    ]


def _issue_files(issues: list[Issue]) -> list[str]:
    paths: set[str] = set()
    for issue in issues:
        path = issue.metadata.get("path")
        if path:
            paths.add(str(path))
        source = str(issue.metadata.get("source", ""))
        if "/" in source or "." in Path(source).name:
            paths.add(source)
        listed_paths = str(issue.metadata.get("paths", ""))
        paths.update(path for path in listed_paths.split(",") if path)
        if issue.location:
            paths.add(issue.location.file_path)
    return sorted(paths)


def _format_files(
    files: list[str], *, markdown: bool, translator: Translator
) -> str:
    if not files:
        return "-"
    shown = files[:3]
    values = [f"`{path}`" if markdown else escape(path) for path in shown]
    suffix = (
        ", +"
        + translator.text("more", "{count} more", count=len(files) - 3)
        if len(files) > 3
        else ""
    )
    return ", ".join(values) + suffix


def _highest_severity(issues: list[Issue]) -> IssueSeverity:
    return max(issues, key=lambda issue: _SEVERITY_WEIGHT[issue.severity]).severity


def _terminal_issue_body(issue: Issue, translator: Translator) -> list[str]:
    if issue.metadata.get("rule_key") == "forbidden_dependency":
        source = issue.metadata.get("source", "")
        target = issue.metadata.get("target", "")
        reason = issue.metadata.get("reason") or translator.text(
            "configured_dependency_violation",
            "This violates configured dependency rules.",
        )
        return [
            translator.text(
                "imports",
                "{source} imports {target}",
                source=escape(str(source)),
                target=escape(str(target)),
            ),
            f"{translator.text('reason', 'Reason')}: {escape(str(reason))}",
        ]
    if issue.metadata.get("rule_key") == "large_function":
        symbol = issue.metadata.get("symbol", issue.title)
        line_count = issue.metadata.get("line_count", "unknown")
        return [
            translator.text(
                "function_lines",
                "{symbol} has {count} lines.",
                symbol=escape(str(symbol)),
                count=line_count,
            )
        ]
    return [escape(translator.issue_description(issue))]


def _terminal_diagnostic(
    diagnostic: AnalysisDiagnostic, translator: Translator
) -> str:
    line = f":{diagnostic.location.start_line}" if diagnostic.location and diagnostic.location.start_line else ""
    return (
        f"[{translator.severity(diagnostic.severity.value).upper()}] "
        f"{escape(diagnostic.file_path)}{line} "
        f"({escape(diagnostic.analyzer)}/{escape(diagnostic.code)}): {escape(diagnostic.message)}"
    )


def _markdown_diagnostic(
    diagnostic: AnalysisDiagnostic, translator: Translator
) -> str:
    line = f":{diagnostic.location.start_line}" if diagnostic.location and diagnostic.location.start_line else ""
    message = diagnostic.message.replace("|", "\\|").replace("\n", " ")
    return (
        f"| {translator.severity(diagnostic.severity.value)} | {diagnostic.analyzer} | "
        f"`{diagnostic.file_path}{line}` | {message} |"
    )


def _suggestions(result: ReviewResult, translator: Translator) -> list[str]:
    suggestions: list[str] = []
    for issue in result.issues:
        suggestion = issue.metadata.get("suggestion")
        if suggestion:
            candidate = str(suggestion)
        elif issue.metadata.get("rule_key") == "large_function":
            candidate = "Consider extracting cohesive responsibilities into smaller functions."
        elif issue.metadata.get("rule_key") == "forbidden_dependency":
            candidate = "Route the dependency through the configured boundary instead of importing it directly."
        else:
            continue
        candidate = translator.suggestion(candidate)
        if not _covered_by_ai(result, issue, candidate):
            suggestions.append(candidate)
    return sorted(dict.fromkeys(suggestions))


def _covered_by_ai(result: ReviewResult, issue: Issue, suggestion: str) -> bool:
    if result.ai_review is None:
        return False
    issue_files = set(_issue_files([issue]))
    for recommendation in result.ai_review.recommendations:
        if issue.id in recommendation.related_issue_ids:
            return True
        recommendation_text = f"{recommendation.title} {recommendation.suggested_action}"
        overlap = _token_overlap(suggestion, recommendation_text)
        related_files = set(recommendation.related_files)
        if overlap >= 0.15 and (not issue_files or not related_files or issue_files & related_files):
            return True
    return False


def _token_overlap(left: str, right: str) -> float:
    left_tokens = _normalized_tokens(left)
    right_tokens = _normalized_tokens(right)
    if not left_tokens or not right_tokens:
        return 0.0
    return len(left_tokens & right_tokens) / len(left_tokens | right_tokens)


def _normalized_tokens(value: str) -> set[str]:
    stop_words = {"a", "an", "and", "consider", "into", "of", "or", "the", "to"}
    tokens = set(re.findall(r"[a-z0-9]+", value.lower())) - stop_words
    return {token.removesuffix("ing") if len(token) > 5 else token for token in tokens}


def output_for_format(format_name: str) -> Output:
    outputs: dict[str, Output] = {
        "terminal": TerminalOutput(),
        "json": JsonOutput(),
        "markdown": MarkdownOutput(),
    }
    try:
        return outputs[format_name]
    except KeyError:
        supported = ", ".join(sorted(outputs))
        raise ValueError(f"Unsupported output format '{format_name}'. Supported formats: {supported}.") from None


def _write_text(destination: str, content: str) -> None:
    path = Path(destination)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content + "\n", encoding="utf-8")


def _translator(result: ReviewResult) -> Translator:
    requested = str(result.metadata.get("output_language", "en"))
    return Translator.for_language(requested)


def _empty_review_state(
    result: ReviewResult, translator: Translator
) -> tuple[str, str | None]:
    scope = result.context.metadata.get("review_scope")
    if scope == "working_tree":
        return (
            translator.text("no_tracked_changes", "No tracked changes found."),
            translator.text(
                "untracked_guidance",
                "Untracked files are not included. Stage them with `git add` before reviewing.",
            ),
        )
    if scope == "branch":
        return (
            translator.text(
                "no_branch_changes",
                "No changes found for the selected branch comparison.",
            ),
            None,
        )
    if scope == "commit":
        return (
            translator.text(
                "no_commit_changes",
                "No changes found for the selected commit.",
            ),
            None,
        )
    return (
        translator.text(
            "no_scope_changes",
            "No changes found for this review scope.",
        ),
        None,
    )
