from __future__ import annotations

import sys
import re
from dataclasses import dataclass
from pathlib import Path

from rich.console import Console
from rich.markup import escape

from sktr_core.model import AnalysisDiagnostic, Issue, IssueSeverity, ReviewResult
from sktr_core.plugins import Output
from sktr_report.artifact import review_result_to_json
from sktr_report.summary import review_breadth, risk_level, risk_score


class TerminalOutput:
    format = "terminal"

    def write(self, result: ReviewResult, destination: str | None = None) -> None:
        content = self.render(result)
        if destination is not None:
            _write_text(destination, content)
            return

        Console(file=sys.stdout).print(content)

    def render(self, result: ReviewResult) -> str:
        score = risk_score(result)
        breadth = review_breadth(result)
        lines = self._summary_lines(result, score, breadth)
        lines.extend(self._changed_file_lines(result))

        if result.issues:
            lines.extend(["", "[bold]Findings[/bold]"])
            lines.extend(self._findings_lines(result.issues))
            lines.extend(["", "[bold]Findings by Category[/bold]"])
            lines.extend(self._category_lines(result.issues))

        if result.diagnostics:
            lines.extend(["", "[bold]Analysis Diagnostics[/bold]"])
            lines.extend(_terminal_diagnostic(diagnostic) for diagnostic in result.diagnostics)

        if result.ai_review is not None:
            lines.extend(self._ai_review_lines(result))

        suggestions = _suggestions(result)
        if suggestions:
            lines.extend(["", "[bold]Suggested Actions[/bold]"])
            lines.extend(f"- {escape(suggestion)}" for suggestion in suggestions)

        if result.messages:
            lines.extend(["", "[bold]Notes[/bold]"])
            lines.extend(f"- {escape(message)}" for message in result.messages)

        lines.extend(self._metadata_lines(result))

        return "\n".join(lines)

    def _summary_lines(self, result: ReviewResult, score: int, breadth: dict[str, int]) -> list[str]:
        lines = [
            "[bold]SKTR Review[/bold]",
            "",
            "[bold]Summary[/bold]",
            f"Risk: {risk_level(score).title()}",
            f"Score: {score}/100",
            f"Changed files: {len(result.context.file_changes)}",
            f"Excluded files: {len(result.context.excluded_files)}",
            f"Issues: {len(result.issues)}",
        ]
        if breadth["production_files"] or breadth["modules"]:
            lines.append(
                f"Review breadth: {breadth['production_files']} production files across "
                f"{breadth['modules']} modules"
            )
        return lines

    def _changed_file_lines(self, result: ReviewResult) -> list[str]:
        if not result.context.file_changes:
            return [f"Status: {result.status}"]
        return [
            "",
            "[bold]Changed Files[/bold]",
            *[
                f"{self._status_label(change.status)} {escape(change.path)}"
                for change in result.context.file_changes
            ],
        ]

    def _metadata_lines(self, result: ReviewResult) -> list[str]:
        lines = ["", "[bold]Metadata[/bold]", "Generated by SKTR.", f"Status: {result.status}"]
        if result.context.metadata.get("review_scope"):
            lines.append(f"Review scope: {result.context.metadata['review_scope']}")
        if result.context.metadata.get("repository_root"):
            lines.append(f"Repository root: {escape(str(result.context.metadata['repository_root']))}")
        return lines

    def _ai_review_lines(self, result: ReviewResult) -> list[str]:
        lines = ["", "[bold]AI Review[/bold]"]
        if result.ai_review.overview:
            lines.extend(["[bold]Overview[/bold]", escape(result.ai_review.overview)])
        if result.ai_review.recommendations:
            lines.append("")
            lines.append("[bold]Prioritized Actions[/bold]")
            lines.extend(self._recommendation_lines(result))
        lines.extend(f"[yellow]Warning:[/yellow] {escape(warning)}" for warning in result.ai_review.warnings)
        return lines

    def _findings_lines(self, issues: list[Issue]) -> list[str]:
        lines: list[str] = []
        groups = _issue_groups(issues)
        for severity in _SEVERITY_ORDER:
            severity_groups = [group for group in groups if group.severity == severity]
            if not severity_groups:
                continue
            if lines:
                lines.append("")
            lines.append(f"[bold]{severity.value.title()}[/bold]")
            for group in severity_groups:
                count = f" ({len(group.issues)} occurrences)" if len(group.issues) > 1 else ""
                lines.append(f"[yellow]⚠[/yellow] {escape(group.title)}{count}")
                if len(group.issues) == 1:
                    lines.extend(f"  {line}" for line in _terminal_issue_body(group.issues[0]))
                else:
                    lines.append(f"  Affected files: {_format_files(_issue_files(group.issues), markdown=False)}")
        return lines

    def _category_lines(self, issues: list[Issue]) -> list[str]:
        lines: list[str] = []
        categories = sorted({issue.category for issue in issues}, key=lambda value: value.value)
        for category in categories:
            category_issues = [issue for issue in issues if issue.category == category]
            lines.append(
                f"{category.value.title()}: {len(category_issues)} issues | "
                f"highest {_highest_severity(category_issues).value.title()} | "
                f"{len(_issue_files(category_issues))} files"
            )
        return lines

    def _recommendation_lines(self, result: ReviewResult) -> list[str]:
        assert result.ai_review is not None
        lines: list[str] = []
        for index, item in enumerate(result.ai_review.recommendations, start=1):
            if index > 1:
                lines.append("")
            lines.extend(
                [
                    f"[bold]{index}. {escape(item.title)}[/bold]",
                    f"   Why: {escape(item.why)}",
                    f"   Suggested action: {escape(item.suggested_action)}",
                ]
            )
            if item.related_files:
                lines.append(f"   Related files: {escape(', '.join(item.related_files))}")
        return lines

    def _status_label(self, status: str) -> str:
        return {
            "added": "A",
            "modified": "M",
            "deleted": "D",
            "renamed": "R",
        }.get(status, "?")

class JsonOutput:
    format = "json"

    def write(self, result: ReviewResult, destination: str | None = None) -> None:
        content = review_result_to_json(result)
        if destination is not None:
            _write_text(destination, content)
            return

        sys.stdout.write(content + "\n")


class MarkdownOutput:
    format = "markdown"

    def write(self, result: ReviewResult, destination: str | None = None) -> None:
        content = self.render(result)
        if destination is not None:
            _write_text(destination, content)
            return

        sys.stdout.write(content + "\n")

    def render(self, result: ReviewResult) -> str:
        score = risk_score(result)
        breadth = review_breadth(result)
        lines = self._summary_lines(result, score, breadth)
        lines.extend(self._changed_file_lines(result))

        if result.issues:
            lines.append("")
            lines.append("## Findings")
            lines.extend(self._issues_by_severity(result.issues))

            lines.append("")
            lines.append("## Findings by Category")
            lines.extend(self._issues_by_category(result.issues))

        if result.diagnostics:
            lines.extend(["", "## Analysis Diagnostics", "| Severity | Analyzer | File | Message |", "|---|---|---|---|"])
            for diagnostic in result.diagnostics:
                lines.append(_markdown_diagnostic(diagnostic))

        if result.ai_review is not None:
            lines.extend(self._ai_review_lines(result))

        suggestions = _suggestions(result)
        if suggestions:
            lines.append("")
            lines.append("## Suggested Actions")
            for suggestion in suggestions:
                lines.append(f"- {suggestion}")

        if result.messages:
            lines.append("")
            lines.append("## Notes")
            lines.extend(f"- {message}" for message in result.messages)

        lines.extend(self._metadata_lines(result))

        return "\n".join(lines)

    def _summary_lines(self, result: ReviewResult, score: int, breadth: dict[str, int]) -> list[str]:
        lines = [
            "# SKTR Review",
            "",
            "## Summary",
            f"Risk: {risk_level(score).title()}  ",
            f"Score: {score}/100  ",
            f"Changed files: {len(result.context.file_changes)}  ",
            f"Excluded files: {len(result.context.excluded_files)}  ",
            f"Issues: {len(result.issues)}",
        ]
        if breadth["production_files"] or breadth["modules"]:
            lines.append(
                f"Review breadth: {breadth['production_files']} production files across "
                f"{breadth['modules']} modules"
            )
        return lines

    def _changed_file_lines(self, result: ReviewResult) -> list[str]:
        lines = ["", "## Changed Files", "| Status | File |", "|---|---|"]
        lines.extend(
            f"| {self._status_label(change.status)} | {change.path} |"
            for change in result.context.file_changes
        )
        if not result.context.file_changes:
            lines.append("| - | No changed files |")
        return lines

    def _ai_review_lines(self, result: ReviewResult) -> list[str]:
        assert result.ai_review is not None
        lines = ["", "## AI Review"]
        if result.ai_review.overview:
            lines.extend(["", "### Overview", result.ai_review.overview])
        if result.ai_review.recommendations:
            lines.extend(["", "### Prioritized Actions"])
            for index, item in enumerate(result.ai_review.recommendations, start=1):
                lines.extend(
                    [
                        "",
                        f"#### {index}. {item.title}",
                        "",
                        f"**Why:** {item.why}",
                        "",
                        f"**Suggested action:** {item.suggested_action}",
                    ]
                )
                if item.related_files:
                    lines.extend(["", "**Related files:**", ""])
                    lines.extend(f"- `{path}`" for path in item.related_files)
        for warning in result.ai_review.warnings:
            lines.extend(["", f"Warning: {warning}"])
        return lines

    def _metadata_lines(self, result: ReviewResult) -> list[str]:
        lines = ["", "## Metadata", "Generated by SKTR.", f"Status: {result.status}"]
        if result.context.metadata.get("review_scope"):
            lines.append(f"Review scope: {result.context.metadata['review_scope']}")
        if result.context.metadata.get("repository_root"):
            lines.append(f"Repository root: {result.context.metadata['repository_root']}")
        return lines

    def _status_label(self, status: str) -> str:
        return {
            "added": "A",
            "modified": "M",
            "deleted": "D",
            "renamed": "R",
        }.get(status, "?")

    def _issues_by_severity(self, issues: list[Issue]) -> list[str]:
        lines: list[str] = []
        groups = _issue_groups(issues)
        for severity in _SEVERITY_ORDER:
            severity_groups = [group for group in groups if group.severity == severity]
            if not severity_groups:
                continue
            lines.append(f"### {severity.value.title()}")
            lines.extend(self._issue_bullets(severity_groups))
        return lines

    def _issues_by_category(self, issues: list[Issue]) -> list[str]:
        lines: list[str] = [
            "| Category | Issues | Highest severity | Affected files | Rules |",
            "|---|---:|---|---|---|",
        ]
        categories = sorted({issue.category for issue in issues}, key=lambda category: category.value)
        for category in categories:
            category_issues = [issue for issue in issues if issue.category == category]
            lines.append(
                "| "
                f"{category.value.title()} | "
                f"{len(category_issues)} | "
                f"{_highest_severity(category_issues).value.title()} | "
                f"{_format_files(_issue_files(category_issues), markdown=True)} | "
                f"{self._rule_names(category_issues)} |"
            )
        return lines

    def _rule_names(self, issues: list[Issue]) -> str:
        rules = sorted({issue.metadata.get("rule_name") or issue.rule_id or "unknown" for issue in issues})
        return ", ".join(str(rule) for rule in rules)

    def _issue_bullets(self, groups: list["_IssueGroup"]) -> list[str]:
        lines: list[str] = []
        for group in groups:
            count = f" ({len(group.issues)} occurrences)" if len(group.issues) > 1 else ""
            lines.append(f"- **{group.title}**{count}")
            if len(group.issues) == 1:
                lines.extend(f"  {line}" for line in self._issue_body(group.issues[0]))
            else:
                lines.append(
                    f"  Affected files: {_format_files(_issue_files(group.issues), markdown=True)}"
                )
        return lines

    def _issue_body(self, issue: Issue) -> list[str]:
        if issue.metadata.get("rule_key") == "forbidden_dependency":
            source = issue.metadata.get("source", "")
            target = issue.metadata.get("target", "")
            reason = issue.metadata.get("reason") or "This violates configured dependency rules."
            return [
                f"`{source}` imports `{target}`.",
                f"Reason: {reason}",
            ]

        if issue.metadata.get("rule_key") == "large_function":
            symbol = issue.metadata.get("symbol", issue.title)
            line_count = issue.metadata.get("line_count", "unknown")
            return [
                f"`{symbol}` has {line_count} lines.",
            ]

        return [issue.description]


_SEVERITY_ORDER = [
    IssueSeverity.CRITICAL,
    IssueSeverity.HIGH,
    IssueSeverity.MEDIUM,
    IssueSeverity.LOW,
    IssueSeverity.INFO,
]

_SEVERITY_WEIGHT = {
    severity: len(_SEVERITY_ORDER) - index
    for index, severity in enumerate(_SEVERITY_ORDER)
}


@dataclass(frozen=True)
class _IssueGroup:
    title: str
    severity: IssueSeverity
    issues: list[Issue]


def _issue_groups(issues: list[Issue]) -> list[_IssueGroup]:
    grouped: dict[tuple[IssueSeverity, str, str | None], list[Issue]] = {}
    for issue in issues:
        grouped.setdefault((issue.severity, issue.title, issue.rule_id), []).append(issue)
    return [
        _IssueGroup(title=title, severity=severity, issues=group_issues)
        for (severity, title, _), group_issues in grouped.items()
    ]


def _issue_files(issues: list[Issue]) -> list[str]:
    paths: set[str] = set()
    for issue in issues:
        path = issue.metadata.get("path")
        if path:
            paths.add(str(path))
        source = str(issue.metadata.get("source", ""))
        if "/" in source or "." in Path(source).name:
            paths.add(source)
        listed_paths = str(issue.metadata.get("paths", ""))
        paths.update(path for path in listed_paths.split(",") if path)
        if issue.location:
            paths.add(issue.location.file_path)
    return sorted(paths)


def _format_files(files: list[str], *, markdown: bool) -> str:
    if not files:
        return "-"
    shown = files[:3]
    values = [f"`{path}`" if markdown else escape(path) for path in shown]
    suffix = f", +{len(files) - 3} more" if len(files) > 3 else ""
    return ", ".join(values) + suffix


def _highest_severity(issues: list[Issue]) -> IssueSeverity:
    return max(issues, key=lambda issue: _SEVERITY_WEIGHT[issue.severity]).severity


def _terminal_issue_body(issue: Issue) -> list[str]:
    if issue.metadata.get("rule_key") == "forbidden_dependency":
        source = issue.metadata.get("source", "")
        target = issue.metadata.get("target", "")
        reason = issue.metadata.get("reason") or "This violates configured dependency rules."
        return [f"{escape(str(source))} imports {escape(str(target))}", f"Reason: {escape(str(reason))}"]
    if issue.metadata.get("rule_key") == "large_function":
        symbol = issue.metadata.get("symbol", issue.title)
        line_count = issue.metadata.get("line_count", "unknown")
        return [f"{escape(str(symbol))} has {line_count} lines."]
    return [escape(issue.description)]


def _terminal_diagnostic(diagnostic: AnalysisDiagnostic) -> str:
    line = f":{diagnostic.location.start_line}" if diagnostic.location and diagnostic.location.start_line else ""
    return (
        f"[{diagnostic.severity.value.upper()}] {escape(diagnostic.file_path)}{line} "
        f"({escape(diagnostic.analyzer)}/{escape(diagnostic.code)}): {escape(diagnostic.message)}"
    )


def _markdown_diagnostic(diagnostic: AnalysisDiagnostic) -> str:
    line = f":{diagnostic.location.start_line}" if diagnostic.location and diagnostic.location.start_line else ""
    message = diagnostic.message.replace("|", "\\|").replace("\n", " ")
    return (
        f"| {diagnostic.severity.value.title()} | {diagnostic.analyzer} | "
        f"`{diagnostic.file_path}{line}` | {message} |"
    )


def _suggestions(result: ReviewResult) -> list[str]:
    suggestions: list[str] = []
    for issue in result.issues:
        suggestion = issue.metadata.get("suggestion")
        if suggestion:
            candidate = str(suggestion)
        elif issue.metadata.get("rule_key") == "large_function":
            candidate = "Consider extracting cohesive responsibilities into smaller functions."
        elif issue.metadata.get("rule_key") == "forbidden_dependency":
            candidate = "Route the dependency through the configured boundary instead of importing it directly."
        else:
            continue
        if not _covered_by_ai(result, issue, candidate):
            suggestions.append(candidate)
    return sorted(dict.fromkeys(suggestions))


def _covered_by_ai(result: ReviewResult, issue: Issue, suggestion: str) -> bool:
    if result.ai_review is None:
        return False
    issue_files = set(_issue_files([issue]))
    for recommendation in result.ai_review.recommendations:
        if issue.id in recommendation.related_issue_ids:
            return True
        recommendation_text = f"{recommendation.title} {recommendation.suggested_action}"
        overlap = _token_overlap(suggestion, recommendation_text)
        related_files = set(recommendation.related_files)
        if overlap >= 0.15 and (not issue_files or not related_files or issue_files & related_files):
            return True
    return False


def _token_overlap(left: str, right: str) -> float:
    left_tokens = _normalized_tokens(left)
    right_tokens = _normalized_tokens(right)
    if not left_tokens or not right_tokens:
        return 0.0
    return len(left_tokens & right_tokens) / len(left_tokens | right_tokens)


def _normalized_tokens(value: str) -> set[str]:
    stop_words = {"a", "an", "and", "consider", "into", "of", "or", "the", "to"}
    tokens = set(re.findall(r"[a-z0-9]+", value.lower())) - stop_words
    return {token.removesuffix("ing") if len(token) > 5 else token for token in tokens}


def output_for_format(format_name: str) -> Output:
    outputs: dict[str, Output] = {
        "terminal": TerminalOutput(),
        "json": JsonOutput(),
        "markdown": MarkdownOutput(),
    }
    try:
        return outputs[format_name]
    except KeyError:
        supported = ", ".join(sorted(outputs))
        raise ValueError(f"Unsupported output format '{format_name}'. Supported formats: {supported}.") from None


def _write_text(destination: str, content: str) -> None:
    path = Path(destination)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content + "\n", encoding="utf-8")
